- name: Set hostname 
  hostname: name={{ inventory_hostname }}

- name: Check for Chrony
  shell: |
    systemctl status chronyd
  ignore_errors: yes
  register: chronyd

- name: Set time with Chrony
  when: chronyd.rc == 0
  shell: |
    systemctl stop chronyd
    chronyd -q 'server pool.ntp.org iburst'
    systemctl start chronyd

- name: Install IPA Server Software
  include_tasks: '{{ item }}' 
  with_first_found:
    - '{{ common_path }}-{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml'
    - '{{ common_path }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
    - '{{ common_path }}-{{ ansible_distribution }}.yml'

- name: Set Resolv Conf
  when: "('ipareplicas' in group_names) and use_dns"
  lineinfile:
    dest: /etc/resolv.conf
    line: nameserver {{ ipareplica_server_ip }}
    insertafter: search.*
    backup: yes

- name: collect facts about system services
  service_facts:

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when:
    - (ansible_facts.services['firewalld.service'] is defined)

- name: collect facts about system services
  service_facts:

- name: Open necessary firewall ports
  firewalld:
    service: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - freeipa-ldap
    - freeipa-ldaps
    - freeipa-replication
    - dns
    - ntp
  when:
    - (ansible_facts.services['firewalld.service'] is defined)
    - (ansible_facts.services['firewalld.service']['state'] == 'running')

- name: Run IPA Replica Install command
#  when: ipareplica.stat.exists == False
  shell:
    ipa-replica-install
    {{ '--setup-ca'
       if use_ca else '' }}
    {{ '--setup-dns --forwarder %s' % ipareplica_forwarders
       if use_dns else '' }}
    {{ '--reverse-zone %s --allow-zone-overlap' % ipareplica_reverse_zones
       if (use_dns and ipareplica_allow_zone_overlap is defined) else '' }}
    {{ '--ip-address=%s' % ansible_default_ipv4.address
       if use_dns else '' }}
    --hostname {{ inventory_hostname }}
    --domain {{ ipaserver_domain }}
    --admin-password  {{ ipaadmin_password }}
    -U > /var/log/ipa-replica-install.command.log 2>&1
